Repository moonad/Moonad, pull requests merged in 2020-10, with the labels that each got.

#93 Add introduction scene
  lib/Mons.Assets.pic_bath.fm
  lib/Mons.Assets.pic_beanstrong.fm
  lib/Mons.Assets.pic_beholder.fm
  lib/Mons.Assets.pic_buff.fm
  lib/Mons.Assets.pic_cobeorn.fm
  lib/Mons.Assets.pic_croni.fm
  lib/Mons.Assets.pic_doomfire.fm
  lib/Mons.Assets.pic_electrowl.fm
  lib/Mons.Assets.pic_elliot.fm
  lib/Mons.Assets.pic_emerelder.fm
  lib/Mons.Assets.pic_espectronus.fm
  lib/Mons.Assets.pic_gaki.fm
  lib/Mons.Assets.pic_gorr.fm
  lib/Mons.Assets.pic_ignite.fm
  lib/Mons.Assets.pic_laugh.fm
  lib/Mons.Assets.pic_lela.fm
  lib/Mons.Assets.pic_mimic.fm
  lib/Mons.Assets.pic_moshy.fm
  lib/Mons.Assets.pic_nameless.fm
  lib/Mons.Assets.pic_noctubright.fm
  lib/Mons.Assets.pic_octoking.fm
  lib/Mons.Assets.pic_poisolick.fm
  lib/Mons.Assets.pic_sandy.fm
  lib/Mons.Assets.pic_sparky.fm
  lib/Mons.Assets.pic_zoio.fm
  lib/Mons.Kind.fm
  lib/Mons.draw.fm
  lib/Mons.fm
  lib/Mons.map_source.fm
Labels: mons

#94 Add type icons
  lib/Mons.Assets.battle_default.fm
  lib/Mons.Assets.pic_frab.fm
  lib/Mons.Assets.pic_slime.fm
  lib/Mons.Char_black.47.fm
  lib/Mons.Char_black.48.fm
  lib/Mons.Char_black.49.fm
  lib/Mons.Char_black.50.fm
  lib/Mons.Char_black.51.fm
  lib/Mons.Char_black.52.fm
  lib/Mons.Char_black.53.fm
  lib/Mons.Char_black.54.fm
  lib/Mons.Char_black.55.fm
  lib/Mons.Char_black.56.fm
  lib/Mons.Char_black.57.fm
  lib/Mons.Char_black.darkness.fm
  lib/Mons.Char_black.earth.fm
  lib/Mons.Char_black.electric.fm
  lib/Mons.Char_black.fire.fm
  lib/Mons.Char_black.grass.fm
  lib/Mons.Char_black.ice.fm
  lib/Mons.Char_black.light.fm
  lib/Mons.Char_black.normal.fm
  lib/Mons.Char_black.psychic.fm
  lib/Mons.Char_black.water.fm
  lib/Mons.Kind.fm
  lib/Mons.draw.fm
  lib/Mons.font_black.fm
  lib/Mons.font_white.fm
  lib/package-lock.json
Labels: moongeon

#95 Add objects
  lib/Mons.Assets.home_bookcase_00.fm
  lib/Mons.Assets.home_bookcase_01.fm
  lib/Mons.Assets.home_carpet_00.fm
  lib/Mons.Assets.home_carpet_01.fm
  lib/Mons.Assets.home_curtain_0.fm
  lib/Mons.Assets.home_dresser_0.fm
  lib/Mons.Assets.home_floor_0.fm
  lib/Mons.Assets.home_sink_00.fm
  lib/Mons.Assets.home_sink_01.fm
  lib/Mons.Assets.home_table_00.fm
  lib/Mons.Assets.home_table_01.fm
  lib/Mons.Assets.home_table_10.fm
  lib/Mons.Assets.home_table_11.fm
  lib/Mons.Assets.home_tv_0.fm
  lib/Mons.Assets.push_tool_off.fm
  lib/Mons.Assets.push_tool_on.fm
  lib/Mons.Kind.fm
  lib/Mons.draw.fm
  lib/Mons.fm
  lib/Mons.map_source.fm
Labels: moongeon

#98 Add lvl 1 and script to generate maps
  lib/Mons.Assets.void.fm
  lib/Mons.Kind.fm
  lib/Mons.fm
  lib/Mons.map_source.fm
Labels: moongeon

#97 Implement Bits.mul
  lib/Bits.mul.fm
  lib/Bits.mul.go.fm
Labels: hacktoberfest-accepted

#100 Small refactoring
  lib/Mons.Assets.battle_azula_d.fm
  lib/Mons.Assets.battle_azula_u.fm
  lib/Mons.Assets.mons_azula_d_0.fm
  lib/Mons.Assets.pic_azula.fm
  lib/Mons.Kind.fm
  lib/Mons.draw.fm
  lib/Mons.fm
  lib/Mons.map_source.fm
Labels: moongeon

#102 Add animation
  lib/Mons.Assets.crystal0.fm
  lib/Mons.Assets.crystal1.fm
  lib/Mons.Assets.crystal2.fm
  lib/Mons.Assets.crystal3.fm
  lib/Mons.Assets.crystal4.fm
  lib/Mons.Assets.crystal5.fm
  lib/Mons.Assets.crystal6.fm
  lib/Mons.Assets.crystal7.fm
  lib/Mons.Assets.fountain_formality_0.fm
  lib/Mons.Assets.fountain_formality_1.fm
  lib/Mons.Assets.fountain_formality_2.fm
  lib/Mons.Assets.fountain_formality_3.fm
  lib/Mons.Kind.fm
  lib/Mons.draw.fm
  lib/Mons.fm
  lib/Mons.map_source.fm
  lib/U32.is_even.fm
Labels: moongeon
